---
title: Haihan.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Haihan Yu(余海晗)
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
